### ISSUE TITLE
1.4 update seems to have broken the mod

### ISSUE THREAD

**Issue by Gina-Ran** [Alexis-Grimm/Un-Limited#18] opened 2022-10-22 22:45 UTC
i have tried several methods of testing this (bionics, armors that enhance stats, etc) and it's fairly clear: anything that boosts stats above 100% is not giving a bonus, but instead a debuff. this only occurs when this mod is installed, otherwise the items behave as normal.

**Comment by Alexis-Grimm** [comment] 2022-10-23 12:08
Could you provide clear steps to reproduce and perhaps some screenshots? I'm not sure what the issue is you've found or how to replicate it

**Comment by Alexis-Grimm** [comment] 2023-05-27 02:19
Closing

**Closed by Alexis-Grimm** 2023-05-27 02:19 UTC
Labels: question
